### ISSUE TITLE
No staellite/ Invalid fix quality

### ISSUE THREAD

**Issue by RT3K** [notchum/dashcam#2]
So i build this dashcam with the pi4 the noir v 2.1 cam and the Beitian BN-180 gps.

This is what i got in the logs:

ERROR: Invalid fix quality
ERROR: No satellite data available
ERROR: Invalid fix quality
ERROR: No satellite data available
ERROR: Invalid fix quality
ERROR: No satellite data available
ERROR: Invalid fix quality
ERROR: No satellite data available
ERROR: Invalid fix quality
ERROR: No satellite data available
ERROR: Invalid fix quality
ERROR: No satellite data available
ERROR: Invalid fix quality
ERROR: No satellite data available
ERROR: Invalid fix quality
ERROR: No satellite data available
ERROR: Invalid fix quality
ERROR: No satellite data available
ERROR: Invalid fix quality

Dont know what the problem is.

**Comment by RT3K** [comment]
I got a fix for that. My dev port is another its not /dev/serial0, in my case its /dev/ttyS0. After changing that in main.py its working now.

**Comment by notchum** [comment]
Great! Glad it works for you :)
